#ifndef MICRONET_LIMITS_H
#define MICRONET_LIMITS_H

#include <stddef.h>
#include <stdint.h>

#define MNET_TRANSPORT_HEADER_SIZE 8U
#define MNET_TRANSPORT_MAX_WIRE_PAYLOAD 512U

#define MNET_SECURITY_HMAC_SIZE 32U
#define MNET_SECURITY_IV_SIZE 16U
#define MNET_SECURITY_ENCRYPT_OVERHEAD (MNET_SECURITY_HMAC_SIZE + MNET_SECURITY_IV_SIZE)

#define MNET_PROTOCOL_SERIALIZED_HEADER_SIZE (1U + 2U + 4U + 32U + 32U + 16U + 2U)

#define MNET_MAX_PUBLIC_PAYLOAD \
    (MNET_TRANSPORT_MAX_WIRE_PAYLOAD - \
     MNET_PROTOCOL_SERIALIZED_HEADER_SIZE - \
     MNET_SECURITY_ENCRYPT_OVERHEAD)

typedef char mnet_public_payload_limit_assert[(MNET_MAX_PUBLIC_PAYLOAD == 375U) ? 1 : -1];

#endif
